### ISSUE TITLE
Black hole causes kick

### ISSUE THREAD

**Issue by mathiascode** [NiLSPACE/Catastrophes#1]
Not sure if you still want to work on this plugin, but currently, black holes cause client kicks. This is the error message:
![screenshot from 2015-10-16 12 30 29](https://cloud.githubusercontent.com/assets/8754153/10538557/f1844fb0-7401-11e5-85b4-a2bf1eb1a7be.png)

**Comment by NiLSPACE** [comment]
@madmaxoft do you perhaps know why this happens? It looks like a packet got too big.

**Comment by madmaxoft** [comment]
I don't think so, I'd expect a different error message for a packet-too-large. This looks more like there's a problem in the SpawnObject packet's ObjectData serializer, it's sending more data than the client expects.
Ref.:
http://wiki.vg/Protocol#Spawn_Object
http://wiki.vg/Object_Data
